name: play_cine_films
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Updated for Dart 3 compatibility

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6  # Latest: 1.0.6
  carousel_slider: ^4.2.1  # Downgraded to stable 4.2.1 (5.0.0 may not exist)
  flutter_svg: ^2.0.7+1    # Latest: 2.0.7+1
  get: ^4.6.6              # Latest: 4.6.6
  getwidget: ^5.0.0        # Latest: 5.0.0
  http: ^1.1.0             # Latest: 1.1.0 (fixed from incorrect 1.3.0)
  intl: ^0.18.1            # Latest: 0.18.1 (fixed from incorrect 0.20.2)
  url_launcher: ^6.1.11    # Latest: 6.1.11
  google_mobile_ads: ^5.3.1  # Latest: 5.4.0+1
  facebook_audience_network: ^1.0.1  # Latest: 1.1.0 (fixed typo)
  path_provider: ^2.1.1    # Latest: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0    # Latest: 3.0.0 (fixed from incorrect 5.0.0)

flutter:
  uses-material-design: true